stages:
  - validate
  - build
  - deploy

variables:
  IMAGE_NAME: "nutrition-planner-frontend"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

validate:
  stage: validate
  tags:
    - fsa-kiiashchenko
  image: node:22-alpine
  script:
    - npm ci
    - npm run build

build:
  stage: build
  tags:
    - fsa-kiiashchenko
  image: docker:28-cli
  services:
    - name: docker:28-dind
      alias: docker
  before_script:
    - until docker info >/dev/null 2>&1; do sleep 2; echo "Cakam na Docker daemon..."; done
    - export IMAGE_VERSION="${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"
    - test -n "$DOCKER_USERNAME" || (echo "Missing DOCKER_USERNAME" && exit 1)
    - test -n "$DOCKER_PASSWORD" || (echo "Missing DOCKER_PASSWORD" && exit 1)
    - test -n "$ACR_REGISTRY" || (echo "Missing ACR_REGISTRY" && exit 1)
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "https://$ACR_REGISTRY"
    - docker build -t "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION" -t "$ACR_REGISTRY/$IMAGE_NAME:latest" .
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION"
    - docker push "$ACR_REGISTRY/$IMAGE_NAME:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  tags:
    - fsa-kiiashchenko
  image: alpine/k8s:1.32.3
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
    - export IMAGE_VERSION="${CI_JOB_ID}-${CI_COMMIT_SHORT_SHA}"
  script:
    - kubectl set image deployment/nutrition-planner-fe nutrition-planner-fe=$ACR_REGISTRY/$IMAGE_NAME:$IMAGE_VERSION -n app
    - kubectl rollout status deployment/nutrition-planner-fe -n app --timeout=120s
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
